/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audeering.opensmile;

class OpenSMILEJNI {

  static {
    try {
      System.loadLibrary("opensmile_jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native int SMILE_LOG_MESSAGE_get();
  public final static native int SMILE_LOG_WARNING_get();
  public final static native int SMILE_LOG_ERROR_get();
  public final static native int SMILE_LOG_DEBUG_get();
  public final static native int SMILE_LOG_PRINT_get();
  public final static native int smilelogmsg_t_type_get(long jarg1, smilelogmsg_t jarg1_);
  public final static native int smilelogmsg_t_level_get(long jarg1, smilelogmsg_t jarg1_);
  public final static native String smilelogmsg_t_text_get(long jarg1, smilelogmsg_t jarg1_);
  public final static native String smilelogmsg_t_module_get(long jarg1, smilelogmsg_t jarg1_);
  public final static native long new_smilelogmsg_t();
  public final static native void delete_smilelogmsg_t(long jarg1);
  public final static native long smile_new();
  public final static native int smile_initialize(long jarg1, String jarg2, String[] jarg3, int jarg5, int jarg6, int jarg7, String jarg8);
  public final static native int smile_run(long jarg1);
  public final static native int smile_abort(long jarg1);
  public final static native int smile_reset(long jarg1);
  public final static native int smile_set_log_callback(long jarg1, long jarg2, long jarg3);
  public final static native int smile_get_state(long jarg1);
  public final static native int smile_set_state_callback(long jarg1, long jarg2, long jarg3);
  public final static native void smile_free(long jarg1);
  public final static native int smile_extsource_write_data(long jarg1, String jarg2, float[] jarg3);
  public final static native int smile_extsource_set_external_eoi(long jarg1, String jarg2);
  public final static native int smile_extaudiosource_write_data(long jarg1, String jarg2, byte[] jarg3);
  public final static native int smile_extaudiosource_set_external_eoi(long jarg1, String jarg2);
  public final static native int smile_extsink_set_data_callback(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int smile_extsink_set_data_callback_ex(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int smile_extsink_get_num_elements(long jarg1, String jarg2, long jarg3);
  public final static native int smile_extsink_get_element_name(long jarg1, String jarg2, int jarg3, long jarg4);
  public final static native int smile_extmsginterface_set_msg_callback(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native int smile_extmsginterface_set_json_msg_callback(long jarg1, String jarg2, long jarg3, long jarg4);
  public final static native String smile_error_msg(long jarg1);
  public final static native boolean callbackfunjson(String jarg1, long jarg2);
  public final static native long new_CallbackExternalMessageInterfaceJson();
  public final static native void delete_CallbackExternalMessageInterfaceJson(long jarg1);
  public final static native boolean CallbackExternalMessageInterfaceJson_onCalledExternalMessageInterfaceJsonCallback(long jarg1, CallbackExternalMessageInterfaceJson jarg1_, String jarg2);
  public final static native long CallbackExternalMessageInterfaceJson_createExternalMessageInterfaceJsonCallback(long jarg1, CallbackExternalMessageInterfaceJson jarg1_);
  public final static native void CallbackExternalMessageInterfaceJson_director_connect(CallbackExternalMessageInterfaceJson obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void CallbackExternalMessageInterfaceJson_change_ownership(CallbackExternalMessageInterfaceJson obj, long cptr, boolean take_or_release);
  public final static native boolean callbackfunextsing(float[] jarg1, long jarg3);
  public final static native long new_CallbackExternalSink();
  public final static native void delete_CallbackExternalSink(long jarg1);
  public final static native boolean CallbackExternalSink_onCalledExternalSinkCallback(long jarg1, CallbackExternalSink jarg1_, float[] jarg2);
  public final static native long CallbackExternalSink_createExternalSinkCallback(long jarg1, CallbackExternalSink jarg1_);
  public final static native void CallbackExternalSink_director_connect(CallbackExternalSink obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void CallbackExternalSink_change_ownership(CallbackExternalSink obj, long cptr, boolean take_or_release);

  public static boolean SwigDirector_CallbackExternalMessageInterfaceJson_onCalledExternalMessageInterfaceJsonCallback(CallbackExternalMessageInterfaceJson jself, String msg) {
    return jself.onCalledExternalMessageInterfaceJsonCallback(msg);
  }
  public static boolean SwigDirector_CallbackExternalSink_onCalledExternalSinkCallback(CallbackExternalSink jself, float[] data) {
    return jself.onCalledExternalSinkCallback(data);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
