/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audeering.opensmile;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;

class OpenSMILE {
  public static SWIGTYPE_p_smileobj_t_ smile_new() {
    long cPtr = OpenSMILEJNI.smile_new();
    return (cPtr == 0) ? null : new SWIGTYPE_p_smileobj_t_(cPtr, false);
  }

  public static smileres_t smile_initialize(SWIGTYPE_p_smileobj_t_ smileobj, String configFile, HashMap<String,String> nOptions, int loglevel, int debug, int consoleOutput, String logFile) {

    Set<String> keyset = nOptions.keySet();
    List<String> params = new ArrayList<> ();
    for (String key : keyset) {
      params.add("-" + key);
      if (nOptions.get(key) != null)
        params.add(nOptions.get(key));
    }
    String[] paramsarray=params.toArray(new String[0]);
    {
      return smileres_t.swigToEnum(OpenSMILEJNI.smile_initialize(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), configFile, paramsarray, loglevel, debug, consoleOutput, logFile));
    }
  }

  public static smileres_t smile_run(SWIGTYPE_p_smileobj_t_ smileobj) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_run(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj)));
  }

  public static smileres_t smile_abort(SWIGTYPE_p_smileobj_t_ smileobj) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_abort(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj)));
  }

  public static smileres_t smile_reset(SWIGTYPE_p_smileobj_t_ smileobj) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_reset(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj)));
  }

  public static smileres_t smile_set_log_callback(SWIGTYPE_p_smileobj_t_ smileobj, SWIGTYPE_p_f_p_smileobj_t__smilelogmsg_t_p_void__void callback, long param) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_set_log_callback(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), SWIGTYPE_p_f_p_smileobj_t__smilelogmsg_t_p_void__void.getCPtr(callback), param));
  }

  public static smilestate_t smile_get_state(SWIGTYPE_p_smileobj_t_ smileobj) {
    return smilestate_t.swigToEnum(OpenSMILEJNI.smile_get_state(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj)));
  }

  public static smileres_t smile_set_state_callback(SWIGTYPE_p_smileobj_t_ smileobj, SWIGTYPE_p_f_p_smileobj_t__enum_smilestate_t_p_void__void callback, long param) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_set_state_callback(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), SWIGTYPE_p_f_p_smileobj_t__enum_smilestate_t_p_void__void.getCPtr(callback), param));
  }

  public static void smile_free(SWIGTYPE_p_smileobj_t_ smileobj) {
    OpenSMILEJNI.smile_free(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj));
  }

  public static smileres_t smile_extsource_write_data(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, float[] data) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extsource_write_data(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, data));
  }

  public static smileres_t smile_extsource_set_external_eoi(SWIGTYPE_p_smileobj_t_ smileobj, String componentName) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extsource_set_external_eoi(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName));
  }

  public static smileres_t smile_extaudiosource_write_data(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, byte[] data) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extaudiosource_write_data(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, data));
  }

  public static smileres_t smile_extaudiosource_set_external_eoi(SWIGTYPE_p_smileobj_t_ smileobj, String componentName) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extaudiosource_set_external_eoi(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName));
  }

  public static smileres_t smile_extsink_set_data_callback(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, SWIGTYPE_p_f_p_q_const__float_long_p_void__bool callback, long param) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extsink_set_data_callback(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, SWIGTYPE_p_f_p_q_const__float_long_p_void__bool.getCPtr(callback), param));
  }

  public static smileres_t smile_extsink_set_data_callback_ex(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, SWIGTYPE_p_f_p_q_const__float_long_long_p_q_const__sExternalSinkMetaDataEx_p_void__bool callback, long param) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extsink_set_data_callback_ex(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, SWIGTYPE_p_f_p_q_const__float_long_long_p_q_const__sExternalSinkMetaDataEx_p_void__bool.getCPtr(callback), param));
  }

  public static smileres_t smile_extsink_get_num_elements(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, SWIGTYPE_p_long numElements) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extsink_get_num_elements(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, SWIGTYPE_p_long.getCPtr(numElements)));
  }

  public static smileres_t smile_extsink_get_element_name(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, int idx, SWIGTYPE_p_p_char elementName) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extsink_get_element_name(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, idx, SWIGTYPE_p_p_char.getCPtr(elementName)));
  }

  public static smileres_t smile_extmsginterface_set_msg_callback(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, SWIGTYPE_p_f_p_q_const__cComponentMessage_p_void__bool callback, long param) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extmsginterface_set_msg_callback(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, SWIGTYPE_p_f_p_q_const__cComponentMessage_p_void__bool.getCPtr(callback), param));
  }

  public static smileres_t smile_extmsginterface_set_json_msg_callback(SWIGTYPE_p_smileobj_t_ smileobj, String componentName, SWIGTYPE_p_f_p_q_const__char_p_void__bool callback, long param) {
    return smileres_t.swigToEnum(OpenSMILEJNI.smile_extmsginterface_set_json_msg_callback(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj), componentName, SWIGTYPE_p_f_p_q_const__char_p_void__bool.getCPtr(callback), param));
  }

  public static String smile_error_msg(SWIGTYPE_p_smileobj_t_ smileobj) {
    return OpenSMILEJNI.smile_error_msg(SWIGTYPE_p_smileobj_t_.getCPtr(smileobj));
  }

  public static boolean callbackfunjson(String msg, long param) {
    return OpenSMILEJNI.callbackfunjson(msg, param);
  }

  public static boolean callbackfunextsing(float[] data, long param) {
    return OpenSMILEJNI.callbackfunextsing(data, param);
  }

}
