/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audeering.opensmile;

public class smilelogmsg_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected smilelogmsg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(smilelogmsg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OpenSMILEJNI.delete_smilelogmsg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public smilelogtype_t getType() {
    return smilelogtype_t.swigToEnum(OpenSMILEJNI.smilelogmsg_t_type_get(swigCPtr, this));
  }

  public int getLevel() {
    return OpenSMILEJNI.smilelogmsg_t_level_get(swigCPtr, this);
  }

  public String getText() {
    return OpenSMILEJNI.smilelogmsg_t_text_get(swigCPtr, this);
  }

  public String getModule() {
    return OpenSMILEJNI.smilelogmsg_t_module_get(swigCPtr, this);
  }

  public smilelogmsg_t() {
    this(OpenSMILEJNI.new_smilelogmsg_t(), true);
  }

}
