/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.audeering.opensmile;

public final class smilestate_t {
  public final static smilestate_t SMILE_UNINITIALIZED = new smilestate_t("SMILE_UNINITIALIZED");
  public final static smilestate_t SMILE_INITIALIZED = new smilestate_t("SMILE_INITIALIZED");
  public final static smilestate_t SMILE_RUNNING = new smilestate_t("SMILE_RUNNING");
  public final static smilestate_t SMILE_ENDED = new smilestate_t("SMILE_ENDED");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static smilestate_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + smilestate_t.class + " with value " + swigValue);
  }

  private smilestate_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private smilestate_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private smilestate_t(String swigName, smilestate_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static smilestate_t[] swigValues = { SMILE_UNINITIALIZED, SMILE_INITIALIZED, SMILE_RUNNING, SMILE_ENDED };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

