/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_OpenSMILE_WRAP_H_
#define SWIG_OpenSMILE_WRAP_H_

class SwigDirector_CallbackExternalMessageInterfaceJson : public CallbackExternalMessageInterfaceJson, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_CallbackExternalMessageInterfaceJson(JNIEnv *jenv);
    virtual ~SwigDirector_CallbackExternalMessageInterfaceJson();
    virtual bool onCalledExternalMessageInterfaceJsonCallback(char const *msg);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};

class SwigDirector_CallbackExternalSink : public CallbackExternalSink, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_CallbackExternalSink(JNIEnv *jenv);
    virtual ~SwigDirector_CallbackExternalSink();
    virtual bool onCalledExternalSinkCallback(float const *data, long vectorSize);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};


#endif
